spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

file:
  upload-dir: /tmp/uploads/ # CI 환경 임시 디렉토리
  url-prefix: /uploads/