spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.test.com
    port: 465
    username: test@test.com
    password: dummy

file:
  upload-dir: /tmp/uploads/
  url-prefix: /uploads/
