name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DB_ID: dummy_user
      DB_PW: dummy_pw
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      NAVER_CLIENT: dummy_naver_client
      NAVER_SECRET: dummy_naver_secret
      KAKAO_CLIENT: dummy_kakao_client
      KAKAO_SECRET: dummy_kakao_secret
      GOOGLE_CLIENT: dummy_google_client
      GOOGLE_SECRET: dummy_google_secret
      MAIL_HOST: smtp.test.com
      MAIL_PORT: 465
      MAIL_EMAIL: test@example.com
      MAIL_PASSWORD: dummy_password
      FILE_DIR: /tmp/uploads

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build -Dspring.profiles.active=ci

  dependency-submission:
    if: github.event_name != 'pull_request'  # PR에서는 실행 안 함
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
